### ISSUE TITLE
installed languages like remora/dynamic on the #+begin_src line ?

### ISSUE THREAD

**Issue by rebcabin** [hasu/emacs-ob-racket#4]
```org
This issue text is snipped from a live org-mode file:

The pre-installed languages like ~racket~ seem to work fine in org-babel:

#+begin_src racket :lang racket
  (+ 3 2)
#+end_src

#+RESULTS:
: 5

I installed the ~remora/dynamic~ language from

    https://github.com/rebcabin/Remora/tree/master/remora

and it works fine from scripts, but not (yet) in org-babel.

If you write a racket file (this one is called ~boof.rkt~:

#+begin_src racket :eval never
  #lang remora/dynamic
  (+ 1 2)
#+end_src

... and then invoke it from bash (Ctrl-C Ctrl-C with cursor inside the
following block):

#+begin_src bash
  racket boof.rkt
#+end_src

#+RESULTS:
: 3

... you get the desired results. However, I have not been able to make
racket find the ~remora/dynamic~ language on the ~#+begin_src~ line:

#+begin_src racket :lang remora/dynamic
  (+ 4 2)
#+end_src

#+RESULTS:
#+begin_example
/tmp/babel-hJt2Sc/org-babel-lOcdzv.rkt:3:8: let: bad syntax
  in: let
  location...:
   /tmp/babel-hJt2Sc/org-babel-lOcdzv.rkt:3:8
  context...:
   do-raise-syntax-error
   /usr/share/racket/collects/racket/private/qq-and-or.rkt:50:20: go
   apply-transformer-in-context
   apply-transformer
   dispatch-transformer
   for-loop
   [repeats 3 more times]
   finish-bodys
   lambda-clause-expander
   for-loop
   loop
   [repeats 1 more time]
   module-begin-k
   expand-module
   expand-capturing-lifts
   temp98_0
   ...
#+end_example

Is there something else I need to do? I tried stepping through the source 
of ~ob-racket.el~ but could not quite find out how to fix the ~#lang~ expansion.
I also tried explicit ~(module foo racket/lang decl...)~ in a ~#+begin_src~ block,
but got other errors from the expansion (e.g., ~module only allowed at top level~)

Any advice for me?

```

**Comment by hasu** [comment]
Given the message "let: bad syntax", the problem would not seem to be 
that the language is not correctly identified, but rather that it is.

As it says in "ob-racket.el",

   The default templates assume that
   `define-values`, `values`, `let`, and `write` have their `racket`
   language semantics.

That's probably not the case for `remora/dynamic`. I don't know how it 
defines `let`, if at all.

If we override the `value-program` template,

   #+begin_src racket :lang remora/dynamic :value-program '(prologue 
"\n" "(write (my-let ()" "\n" define-vars "\n" :body "))" "\n" epilogue)
     (+ 4 2)
   #+end_src

then we'll get a similar complaint, but about `my-let`.

When you run "boof.rkt" directly from a bash block, then there are no 
ob-racket templates involved, and the program works, presumably printing 
out its top-level results.

We can make the same thing happen by evaluating the block

   #+begin_src racket :lang remora/dynamic :results output
     (+ 4 2)
   #+end_src

in which case the less language-sensitive `output-program` template gets 
used to generate the program to run.

If variables are defined, then further customization of the templates is 
required. It won't work to write

   #+begin_src racket :lang remora/dynamic :results output :var x=4 y=2
     (+ x y)
   #+end_src

but we can override the `define-var` template

   #+begin_src racket :lang remora/dynamic :results output :var x=4 y=2 
:define-var '(parens (spaced "def" var-name var-value))
     (+ x y)
   #+end_src

**Comment by rebcabin** [comment]
I'm grateful for your kind, swift, and precise reply. You have definitely improved my affairs, here! I now know where to look to solve further problems.
