### ISSUE TITLE
racket command not found

### ISSUE THREAD

**Issue by borgauf** [hasu/emacs-ob-racket#9]
I've got racket-mode installed and working. I've got this in my init

(add-to-list 'load-path "/home/galaxybeing/.emacs.d/modes/emacs-ob-racket")
(require 'ob-racket)

as well as 

(org-babel-do-load-languages
 (quote org-babel-load-languages)
 (quote ((emacs-lisp . t)
         (racket . t)
...

The variable racket-program is set to the racket executable /home/galaxybeing/opt/racket-8.12/bin/racket (again, racket-mode works.)

But when I try your EXAMPLES.org blocks with C-c C-c I get 

racket command not found

**Comment by hasu** [comment]
I assume then that you don't have the "racket" executable on your PATH 
(at least not for the Emacs process), which is what ob-racket assumes by 
default. It's written not to refer to racket-mode specific settings such 
as `racket-program'.

You can try additionally setting

   (setq ob-racket-custom-command-templates
     `((racket . ,racket-program)))

**Comment by borgauf** [comment]
That worked. Thank you.
